#!/usr/bin/env bash
# Starts the Convex local backend, generates an admin key, deploys functions,
# and (on first run) seeds demo data — all without cloud API access.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
CLIENT_DIR="$REPO_ROOT/client"
BINARY="$HOME/.cache/convex/binaries/precompiled-2026-04-27-b603022/convex-local-backend"
DB_PATH="$CLIENT_DIR/convex_local_backend.sqlite3"
INSTANCE_NAME="anonymous-agent"
INSTANCE_SECRET="4361726e697461732c206c69746572616c6c79206d65616e696e6720226c6974"
PORT=3210
ENV_FILE="$CLIENT_DIR/.env.local"

# ── 1. Stop any running backend ─────────────────────────────────────────────
if pgrep -f convex-local-backend > /dev/null 2>&1; then
  echo "→ Stopping existing Convex backend..."
  pkill -f convex-local-backend || true
  sleep 1
fi

# ── 2. Start the backend binary ─────────────────────────────────────────────
echo "→ Starting Convex local backend on port $PORT..."
"$BINARY" \
  --instance-name "$INSTANCE_NAME" \
  --instance-secret "$INSTANCE_SECRET" \
  "$DB_PATH" \
  > /tmp/convex-backend.log 2>&1 &
BACKEND_PID=$!

# Wait until the backend is ready
echo -n "   Waiting for backend"
for i in $(seq 1 30); do
  if curl -s "http://127.0.0.1:$PORT/version" > /dev/null 2>&1; then
    echo " ready!"
    break
  fi
  echo -n "."
  sleep 0.5
done

if ! curl -s "http://127.0.0.1:$PORT/version" > /dev/null 2>&1; then
  echo ""
  echo "✖ Backend failed to start. See /tmp/convex-backend.log"
  exit 1
fi

# ── 3. Generate admin key ────────────────────────────────────────────────────
echo "→ Generating admin key..."
ADMIN_KEY=$(INSTANCE_NAME="$INSTANCE_NAME" INSTANCE_SECRET="$INSTANCE_SECRET" \
  node "$REPO_ROOT/gen-admin-key.mjs")

# ── 4. Write .env.local ──────────────────────────────────────────────────────
echo "→ Writing $ENV_FILE..."
cat > "$ENV_FILE" << EOF
# Convex local backend — generated by start-convex.sh
CONVEX_SELF_HOSTED_URL=http://127.0.0.1:$PORT
CONVEX_SELF_HOSTED_ADMIN_KEY=$ADMIN_KEY
VITE_CONVEX_URL=http://127.0.0.1:$PORT
EOF

# ── 5. Deploy Convex functions ───────────────────────────────────────────────
echo "→ Deploying Convex functions..."
(cd "$CLIENT_DIR" && npx convex dev --once)

# ── 6. Seed demo data (idempotent — skips if already seeded) ─────────────────
echo "→ Seeding demo data..."
RESULT=$(curl -s -X POST "http://127.0.0.1:$PORT/api/mutation" \
  -H "Authorization: Convex $ADMIN_KEY" \
  -H "Content-Type: application/json" \
  -d '{"path":"seed:seedAlbums","args":{},"format":"convex_encoded_json"}')
echo "   $RESULT"

echo ""
echo "✔ Convex backend running (PID $BACKEND_PID)"
echo "  Backend URL : http://127.0.0.1:$PORT"
echo "  Admin key   : $ADMIN_KEY"
echo ""
echo "  Start the dev server: cd client && npm run dev"
