/* eslint-disable */
// This file is auto-generated by `npx convex dev`. Re-run to update.
export {
  queryGeneric as query,
  mutationGeneric as mutation,
  actionGeneric as action,
  internalQueryGeneric as internalQuery,
  internalMutationGeneric as internalMutation,
  internalActionGeneric as internalAction,
} from 'convex/server'
